import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
export const metadata = {
	title: "Positivus Website",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="font-grotesk bg-white">
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
